# Generated by Django 3.0.5 on 2020-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonic',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
