# Generated by Django 3.0.5 on 2020-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0002_ultrasonic_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonic',
            name='snippet',
            field=models.TextField(default='Type only 3 points for display in product box', max_length=300),
        ),
    ]
