# Generated by Django 3.0.5 on 2020-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0003_ultrasonic_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasonic',
            name='slug',
            field=models.SlugField(default='This is the URL'),
        ),
    ]
