# Generated by Django 3.0.5 on 2020-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0004_auto_20200614_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasonic',
            name='snippet',
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='snippet1',
            field=models.TextField(default='Type only 1 line for display in product box', max_length=80),
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='snippet2',
            field=models.TextField(default='Type only 1 line for display in product box', max_length=80),
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='snippet3',
            field=models.TextField(default='Type only 1 line for display in product box', max_length=80),
        ),
    ]
