# Generated by Django 3.0.5 on 2020-06-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0006_bot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
