# Generated by Django 3.0.5 on 2020-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decade_Resistance_Box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade_resistance_box',
            name='body',
        ),
        migrations.AddField(
            model_name='decade_resistance_box',
            name='file',
            field=models.FileField(default='default.pdf', upload_to=''),
        ),
    ]
