# Generated by Django 3.0.5 on 2020-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20200613_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
