# Generated by Django 3.0.5 on 2020-06-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20200613_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='thumb',
            new_name='thumb1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='title1',
        ),
    ]
