# Generated by Django 3.0.5 on 2020-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20200613_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thumb2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumb3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumb4',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumb5',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumb6',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title2',
            field=models.TextField(default='title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title3',
            field=models.TextField(default='title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title4',
            field=models.TextField(default='title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title5',
            field=models.TextField(default='title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title6',
            field=models.TextField(default='title', max_length=50),
        ),
    ]
