# Generated by Django 3.0.5 on 2020-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halleffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='This is the URL')),
                ('snippet1', models.TextField(default='Type only 1 line for display in product box', max_length=80)),
                ('snippet2', models.TextField(default='Type only 1 line for display in product box', max_length=80)),
                ('snippet3', models.TextField(default='Type only 1 line for display in product box', max_length=80)),
                ('file', models.FileField(default='default.pdf', upload_to='')),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
